using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Reflection;
using System.Text.Json.Serialization;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using pysical_model_api.Data;
using System.Linq.Expressions;
using System.Security.Cryptography.X509Certificates;
using System.Globalization;

namespace pysical_model_api.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class PredictionDataController : ControllerBase
    {
        private readonly ILogger<PredictionDataController> _logger;

        public PredictionDataController(ILogger<PredictionDataController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public async Task<IEnumerable<PredictionData>> Get()
        {
            var windforecast = await GetWeatherData();

            var predictionData = new List<PredictionData>();

            foreach(var forecast in windforecast)
            {
                var data = new PredictionData
                {
                    forecastDateTime = forecast.forecastDateTime,
                    windspeed = forecast.windspeed,
                    winddirection = ChangeWindDir(forecast.winddir),
                    yawposition = GetYawPositionByWindDirection(forecast.winddir),
                    bladepitch1 = 2.0,
                    bladepitch2 = 2.0,
                    bladepitch3 = 2.0
                };
                predictionData.Add(data);
            }

            return predictionData;
        }

        private double GetYawPositionByWindDirection(double winddirection)
        {
            return winddirYawpos.Aggregate((x, y) => Math.Abs(x.WinDir - winddirection) < Math.Abs(y.WinDir - winddirection) ? x : y).YawPosition;
        }

        private static double Interpolate(DateTime x0, double y0, DateTime x1, double y1, DateTime target)
        {
            if (y0 == y1) return y0;
            var totalsec = (x1 - x0).TotalSeconds;
            double rate = (y1 - y0) / totalsec ;
            double xDistance = totalsec - (x1 - target).TotalSeconds;
            //and then return the datetime that goes along with that point
            return rate * xDistance + y0;
        }

        private double ChangeWindDir(double windirection360)
        {
            if (windirection360 >= 0 && windirection360 < 180) return windirection360;
            else return -(360.0 - windirection360);
        }

        private async Task<IEnumerable<WindForecastData>> GetWeatherData()
        {
            // date
            var koreaNow = DateTime.UtcNow.AddHours(9.0);
            var reqDate = koreaNow.ToString("yyyyMMdd");
            // time
            //0200, 0500, 0800, 1100, 1400, 1700, 2000, 2300 
            var reqTime = GetRequestTime(koreaNow);
            
            var url = new Uri($"http://apis.data.go.kr/1360000/VilageFcstInfoService/getVilageFcst?ServiceKey=JD8neHEIVm%2B8hNZTti14MhWSGJWLg2aORWfaRUsQWQ1MohI7q5nmA92E160fByvJg3bTbz1aIGFK0NiDICpBLg%3D%3D&pageNo=1&numOfRows=300&dataType=JSON&nx=46&ny=35&base_date={reqDate}&base_time={reqTime}");
            string result;
            using (HttpClient client = new HttpClient())
            {
                try
                {
                    result = await client.GetStringAsync(url);
                }
                catch (Exception ex)
                {
                    _logger.LogError(ex.ToString());
                    throw new Exception("Weather API error", ex);
                }
            }

            var weatherData = JsonConvert.DeserializeObject<WeatherData>(result);
            var tomorrow = koreaNow.AddDays(1).ToString("yyyyMMdd");
            CultureInfo provider = CultureInfo.InvariantCulture;

            var weatherForecastData = weatherData.response.body.items.item
                .Where(x => x.fcstDate == tomorrow && x.category == "VEC")
                .Select(x => new WindForecastData {
                    forecastDateTime = DateTime.ParseExact(x.fcstDate + x.fcstTime, "yyyyMMddHHmm", provider),
                    winddir = double.Parse(x.fcstValue)
                }).ToList();

            foreach(var wfd in weatherForecastData)
            {
                wfd.windspeed = weatherData.response.body.items.item.Where(x => x.category == "WSD" &&
                                                        x.fcstDate == wfd.forecastDateTime.ToString("yyyyMMdd") &&
                                                        x.fcstTime == wfd.forecastDateTime.ToString("HHmm")).Select(x => double.Parse(x.fcstValue))
                                                    .FirstOrDefault();
            }
            
            return weatherForecastData;
        }

        private string GetRequestTime(DateTime date)
        {
            var validTimes = new string[] { "0200", "0500", "0800", "1100", "1400", "1700", "2000", "2300" };
            int index;
            var hour = date.Hour;
            var minute = date.Minute;
            var time = date.Hour * 100 + date.Minute;

            if (time > 210 && time <= 510) index = 0;
            else if (time > 510 && time <= 810) index = 1;
            else if (time > 810 && time <= 1110) index = 2;
            else if (time > 1110 && time <= 1410) index = 3;
            else if (time > 1410 && time <= 1710) index = 4;
            else if (time > 1710 && time <= 2010) index = 5;
            else if (time > 2010 && time <= 2310) index = 6;
            else index = 7;

            return validTimes[index];
        }

        List<WindirYawpos> winddirYawpos = new List<WindirYawpos>()
        {
            new WindirYawpos { WinDir =     38.9    , YawPosition =     -131.26  },
            new WindirYawpos { WinDir =     38.8    , YawPosition =     -131.48  },
            new WindirYawpos { WinDir =     38.9    , YawPosition =     -131.48  },
            new WindirYawpos { WinDir =     38.6    , YawPosition =     -131.05  },
            new WindirYawpos { WinDir =     38.5    , YawPosition =     -131.71  },
            new WindirYawpos { WinDir =     38.4    , YawPosition =     -130.83  },
            new WindirYawpos { WinDir =     38.3    , YawPosition =     -131.94  },
            new WindirYawpos { WinDir =     38.2    , YawPosition =     -130.4   },
            new WindirYawpos { WinDir =     38  , YawPosition =     -130.18  },
            new WindirYawpos { WinDir =     37.8    , YawPosition =     -132.16  },
            new WindirYawpos { WinDir =     37.6    , YawPosition =     -129.95  },
            new WindirYawpos { WinDir =     37.5    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     37.4    , YawPosition =     -132.36  },
            new WindirYawpos { WinDir =     37.3    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     37.2    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     37.1    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     37  , YawPosition =     -132.57  },
            new WindirYawpos { WinDir =     36.9    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     36.8    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     36.7    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     36.6    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     36.5    , YawPosition =     -129.52  },
            new WindirYawpos { WinDir =     36.4    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     36.3    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     36.2    , YawPosition =     -132.81  },
            new WindirYawpos { WinDir =     36.1    , YawPosition =     -129.31  },
            new WindirYawpos { WinDir =     36  , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     35.8    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     35.7    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     35.6    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     35.5    , YawPosition =     -133.03  },
            new WindirYawpos { WinDir =     35.4    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     35.3    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     35.2    , YawPosition =     -129.07  },
            new WindirYawpos { WinDir =     35.1    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     35  , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     34.9    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     34.8    , YawPosition =     -133.23  },
            new WindirYawpos { WinDir =     34.7    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     34.6    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     34.5    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     34.3    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     34.2    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     34.1    , YawPosition =     -128.85  },
            new WindirYawpos { WinDir =     34  , YawPosition =     -133.46  },
            new WindirYawpos { WinDir =     33.9    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     33.8    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     33.7    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     33.6    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     33.5    , YawPosition =     -128.63  },
            new WindirYawpos { WinDir =     33.4    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     33.3    , YawPosition =     -133.69  },
            new WindirYawpos { WinDir =     33.2    , YawPosition =     -153.58  },
            new WindirYawpos { WinDir =     33.1    , YawPosition =     -128.4   },
            new WindirYawpos { WinDir =     33  , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     32.9    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     32.8    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     32.7    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     32.6    , YawPosition =     -133.91  },
            new WindirYawpos { WinDir =     32.5    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     32.4    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     32.3    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     32.2    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     32.1    , YawPosition =     -128.2   },
            new WindirYawpos { WinDir =     32  , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     31.9    , YawPosition =     -134.13  },
            new WindirYawpos { WinDir =     31.8    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     31.6    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     31.5    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     31.4    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     31.3    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     31.2    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     31.1    , YawPosition =     -134.35  },
            new WindirYawpos { WinDir =     31  , YawPosition =     -127.97  },
            new WindirYawpos { WinDir =     30.9    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     30.8    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     30.7    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     30.6    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     30.5    , YawPosition =     -134.58  },
            new WindirYawpos { WinDir =     30.4    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     30.3    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     30.2    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     30.1    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     30  , YawPosition =     -134.78  },
            new WindirYawpos { WinDir =     29.9    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     29.8    , YawPosition =     -127.74  },
            new WindirYawpos { WinDir =     29.7    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     29.6    , YawPosition =     -134.82  },
            new WindirYawpos { WinDir =     29.5    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     29.4    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     29.3    , YawPosition =     -134.89  },
            new WindirYawpos { WinDir =     29.2    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     29  , YawPosition =     -134.89  },
            new WindirYawpos { WinDir =     28.8    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     28.7    , YawPosition =     -148.51  },
            new WindirYawpos { WinDir =     28.6    , YawPosition =     -127.53  },
            new WindirYawpos { WinDir =     28.5    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     28.4    , YawPosition =     -134.89  },
            new WindirYawpos { WinDir =     28.3    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     28  , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     27.9    , YawPosition =     -148.07  },
            new WindirYawpos { WinDir =     27.8    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     27.6    , YawPosition =     -134.89  },
            new WindirYawpos { WinDir =     27.5    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     27.4    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     27.3    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     27.2    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     27.1    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     27  , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     26.9    , YawPosition =     -134.89  },
            new WindirYawpos { WinDir =     26.8    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     26.7    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     26.6    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     26.5    , YawPosition =     -127.09  },
            new WindirYawpos { WinDir =     26.4    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     26.3    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     26.2    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     26.1    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     26  , YawPosition =     -134.89  },
            new WindirYawpos { WinDir =     25.9    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     25.8    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     25.7    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     25.6    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     25.5    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     25.4    , YawPosition =     -134.89  },
            new WindirYawpos { WinDir =     25.3    , YawPosition =     -126.88  },
            new WindirYawpos { WinDir =     25.2    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     25.1    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     25  , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     24.9    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     24.8    , YawPosition =     -134.89  },
            new WindirYawpos { WinDir =     24.7    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     24.6    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     24.5    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     24.4    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     24.3    , YawPosition =     -134.89  },
            new WindirYawpos { WinDir =     24.1    , YawPosition =     -134.89  },
            new WindirYawpos { WinDir =     24  , YawPosition =     -126.64  },
            new WindirYawpos { WinDir =     23.9    , YawPosition =     -134.89  },
            new WindirYawpos { WinDir =     23.8    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     23.7    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     23.5    , YawPosition =     -134.89  },
            new WindirYawpos { WinDir =     23.4    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     23.3    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     23.2    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     23  , YawPosition =     -134.89  },
            new WindirYawpos { WinDir =     22.9    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     22.8    , YawPosition =     -126.43  },
            new WindirYawpos { WinDir =     22.7    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     22.6    , YawPosition =     -138.38  },
            new WindirYawpos { WinDir =     22.5    , YawPosition =     -134.89  },
            new WindirYawpos { WinDir =     22.4    , YawPosition =     -134.89  },
            new WindirYawpos { WinDir =     22.3    , YawPosition =     -139.89  },
            new WindirYawpos { WinDir =     22.2    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     22.1    , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     22  , YawPosition =     -137.48  },
            new WindirYawpos { WinDir =     21.9    , YawPosition =     -134.89  },
            new WindirYawpos { WinDir =     21.8    , YawPosition =     -126.21  },
            new WindirYawpos { WinDir =     21.7    , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     21.6    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     21.5    , YawPosition =     -154.6   },
            new WindirYawpos { WinDir =     21.4    , YawPosition =     -137.25  },
            new WindirYawpos { WinDir =     21.3    , YawPosition =     -140.35  },
            new WindirYawpos { WinDir =     21.2    , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     21.1    , YawPosition =     -137.06  },
            new WindirYawpos { WinDir =     21  , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     20.9    , YawPosition =     -140.58  },
            new WindirYawpos { WinDir =     20.8    , YawPosition =     -134.89  },
            new WindirYawpos { WinDir =     20.7    , YawPosition =     -140.79  },
            new WindirYawpos { WinDir =     20.6    , YawPosition =     -120.38  },
            new WindirYawpos { WinDir =     20.5    , YawPosition =     -126     },
            new WindirYawpos { WinDir =     20.4    , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     20.3    , YawPosition =     -141.01  },
            new WindirYawpos { WinDir =     20.2    , YawPosition =     -120.38  },
            new WindirYawpos { WinDir =     20.1    , YawPosition =     -120.38  },
            new WindirYawpos { WinDir =     20  , YawPosition =     -120.38  },
            new WindirYawpos { WinDir =     19.9    , YawPosition =     -125.27  },
            new WindirYawpos { WinDir =     19.8    , YawPosition =     -120.38  },
            new WindirYawpos { WinDir =     19.7    , YawPosition =     -120.38  },
            new WindirYawpos { WinDir =     19.6    , YawPosition =     -124.83  },
            new WindirYawpos { WinDir =     19.5    , YawPosition =     -120.38  },
            new WindirYawpos { WinDir =     19.4    , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     19.3    , YawPosition =     -134.89  },
            new WindirYawpos { WinDir =     19.2    , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     19.1    , YawPosition =     -127.03  },
            new WindirYawpos { WinDir =     19  , YawPosition =     -120.38  },
            new WindirYawpos { WinDir =     18.9    , YawPosition =     -125.83  },
            new WindirYawpos { WinDir =     18.8    , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     18.7    , YawPosition =     -120.38  },
            new WindirYawpos { WinDir =     18.6    , YawPosition =     -125.83  },
            new WindirYawpos { WinDir =     18.5    , YawPosition =     -123.98  },
            new WindirYawpos { WinDir =     18.4    , YawPosition =     -141.44  },
            new WindirYawpos { WinDir =     18.3    , YawPosition =     -120.38  },
            new WindirYawpos { WinDir =     18.2    , YawPosition =     -120.38  },
            new WindirYawpos { WinDir =     18.1    , YawPosition =     -123.75  },
            new WindirYawpos { WinDir =     18  , YawPosition =     -118.55  },
            new WindirYawpos { WinDir =     17.9    , YawPosition =     -118.11  },
            new WindirYawpos { WinDir =     17.8    , YawPosition =     -125.83  },
            new WindirYawpos { WinDir =     17.7    , YawPosition =     -118.78  },
            new WindirYawpos { WinDir =     17.6    , YawPosition =     -125.83  },
            new WindirYawpos { WinDir =     17.5    , YawPosition =     -117.88  },
            new WindirYawpos { WinDir =     17.4    , YawPosition =     -125.83  },
            new WindirYawpos { WinDir =     17.3    , YawPosition =     -120.38  },
            new WindirYawpos { WinDir =     17.2    , YawPosition =     -125.35  },
            new WindirYawpos { WinDir =     17.1    , YawPosition =     -119.01  },
            new WindirYawpos { WinDir =     17  , YawPosition =     -120.38  },
            new WindirYawpos { WinDir =     16.9    , YawPosition =     -120.38  },
            new WindirYawpos { WinDir =     16.8    , YawPosition =     -117.66  },
            new WindirYawpos { WinDir =     16.7    , YawPosition =     -120.73  },
            new WindirYawpos { WinDir =     16.6    , YawPosition =     -119.23  },
            new WindirYawpos { WinDir =     16.5    , YawPosition =     -119.21  },
            new WindirYawpos { WinDir =     16.4    , YawPosition =     -117.45  },
            new WindirYawpos { WinDir =     16.3    , YawPosition =     -120.38  },
            new WindirYawpos { WinDir =     16.2    , YawPosition =     -125.11  },
            new WindirYawpos { WinDir =     16.1    , YawPosition =     -119     },
            new WindirYawpos { WinDir =     16  , YawPosition =     -120.38  },
            new WindirYawpos { WinDir =     15.9    , YawPosition =     -117.24  },
            new WindirYawpos { WinDir =     15.8    , YawPosition =     -125.83  },
            new WindirYawpos { WinDir =     15.7    , YawPosition =     -127.51  },
            new WindirYawpos { WinDir =     15.6    , YawPosition =     -119.31  },
            new WindirYawpos { WinDir =     15.5    , YawPosition =     -117.01  },
            new WindirYawpos { WinDir =     15.4    , YawPosition =     -119.41  },
            new WindirYawpos { WinDir =     15.3    , YawPosition =     -108.21  },
            new WindirYawpos { WinDir =     15.2    , YawPosition =     -119.41  },
            new WindirYawpos { WinDir =     15.1    , YawPosition =     -108.42  },
            new WindirYawpos { WinDir =     15  , YawPosition =     -123.92  },
            new WindirYawpos { WinDir =     14.9    , YawPosition =     -119.41  },
            new WindirYawpos { WinDir =     14.8    , YawPosition =     -107.77  },
            new WindirYawpos { WinDir =     14.7    , YawPosition =     -119.41  },
            new WindirYawpos { WinDir =     14.6    , YawPosition =     -119.41  },
            new WindirYawpos { WinDir =     14.5    , YawPosition =     -108.63  },
            new WindirYawpos { WinDir =     14.4    , YawPosition =     -109.05  },
            new WindirYawpos { WinDir =     14.3    , YawPosition =     -118.68  },
            new WindirYawpos { WinDir =     14.2    , YawPosition =     -119.41  },
            new WindirYawpos { WinDir =     14.1    , YawPosition =     -118.68  },
            new WindirYawpos { WinDir =     14  , YawPosition =     -109.23  },
            new WindirYawpos { WinDir =     13.9    , YawPosition =     -109.3   },
            new WindirYawpos { WinDir =     13.8    , YawPosition =     -109.37  },
            new WindirYawpos { WinDir =     13.7    , YawPosition =     -107.17  },
            new WindirYawpos { WinDir =     13.6    , YawPosition =     -118.68  },
            new WindirYawpos { WinDir =     13.5    , YawPosition =     -118.16  },
            new WindirYawpos { WinDir =     13.4    , YawPosition =     -109.37  },
            new WindirYawpos { WinDir =     13.3    , YawPosition =     -117.94  },
            new WindirYawpos { WinDir =     13.2    , YawPosition =     -109.37  },
            new WindirYawpos { WinDir =     13.1    , YawPosition =     -119.41  },
            new WindirYawpos { WinDir =     13  , YawPosition =     -106.88  },
            new WindirYawpos { WinDir =     12.9    , YawPosition =     -119.41  },
            new WindirYawpos { WinDir =     12.8    , YawPosition =     -119.41  },
            new WindirYawpos { WinDir =     12.7    , YawPosition =     -109.37  },
            new WindirYawpos { WinDir =     12.6    , YawPosition =     -117.68  },
            new WindirYawpos { WinDir =     12.5    , YawPosition =     -118.68  },
            new WindirYawpos { WinDir =     12.4    , YawPosition =     -119.41  },
            new WindirYawpos { WinDir =     12.3    , YawPosition =     -118.68  },
            new WindirYawpos { WinDir =     12.2    , YawPosition =     -119.41  },
            new WindirYawpos { WinDir =     12.1    , YawPosition =     -117.53  },
            new WindirYawpos { WinDir =     12  , YawPosition =     -109.37  },
            new WindirYawpos { WinDir =     11.9    , YawPosition =     -106.64  },
            new WindirYawpos { WinDir =     11.8    , YawPosition =     -118.02  },
            new WindirYawpos { WinDir =     11.7    , YawPosition =     -117.24  },
            new WindirYawpos { WinDir =     11.6    , YawPosition =     -109.37  },
            new WindirYawpos { WinDir =     11.5    , YawPosition =     -112.04  },
            new WindirYawpos { WinDir =     11.4    , YawPosition =     -118.7   },
            new WindirYawpos { WinDir =     11.3    , YawPosition =     -118.2   },
            new WindirYawpos { WinDir =     11.2    , YawPosition =     -118.02  },
            new WindirYawpos { WinDir =     11.1    , YawPosition =     -118.48  },
            new WindirYawpos { WinDir =     11  , YawPosition =     -119.41  },
            new WindirYawpos { WinDir =     10.9    , YawPosition =     -106.46  },
            new WindirYawpos { WinDir =     10.8    , YawPosition =     -109.37  },
            new WindirYawpos { WinDir =     10.7    , YawPosition =     -110.65  },
            new WindirYawpos { WinDir =     10.6    , YawPosition =     -110.65  },
            new WindirYawpos { WinDir =     10.5    , YawPosition =     -110.65  },
            new WindirYawpos { WinDir =     10.4    , YawPosition =     -118.68  },
            new WindirYawpos { WinDir =     10.3    , YawPosition =     -118.02  },
            new WindirYawpos { WinDir =     10.2    , YawPosition =     -111.97  },
            new WindirYawpos { WinDir =     10.1    , YawPosition =     -110.65  },
            new WindirYawpos { WinDir =     10  , YawPosition =     -116.86  },
            new WindirYawpos { WinDir =     9.900001    , YawPosition =     -109.37  },
            new WindirYawpos { WinDir =     9.8 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     9.7 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     9.6 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     9.5 , YawPosition =     -112.04  },
            new WindirYawpos { WinDir =     9.400001    , YawPosition =     -109.37  },
            new WindirYawpos { WinDir =     9.3 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     9.2 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     9.1 , YawPosition =     -110.65  },
            new WindirYawpos { WinDir =     9   , YawPosition =     -118.68  },
            new WindirYawpos { WinDir =     8.900001    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     8.8 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     8.7 , YawPosition =     -109.37  },
            new WindirYawpos { WinDir =     8.6 , YawPosition =     -110.65  },
            new WindirYawpos { WinDir =     8.5 , YawPosition =     -110.65  },
            new WindirYawpos { WinDir =     8.400001    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     8.3 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     8.2 , YawPosition =     -110.65  },
            new WindirYawpos { WinDir =     8.1 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     8   , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     7.9 , YawPosition =     -109.37  },
            new WindirYawpos { WinDir =     7.8 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     7.7 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     7.6 , YawPosition =     -105.8   },
            new WindirYawpos { WinDir =     7.5 , YawPosition =     -109.37  },
            new WindirYawpos { WinDir =     7.4 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     7.3 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     7.2 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     7.1 , YawPosition =     -109.37  },
            new WindirYawpos { WinDir =     7   , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     6.9 , YawPosition =     -105.55  },
            new WindirYawpos { WinDir =     6.8 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     6.7 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     6.6 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     6.5 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     6.4 , YawPosition =     -109.37  },
            new WindirYawpos { WinDir =     6.3 , YawPosition =     -105.38  },
            new WindirYawpos { WinDir =     6.2 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     6.1 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     6   , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     5.9 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     5.8 , YawPosition =     -109.37  },
            new WindirYawpos { WinDir =     5.7 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     5.6 , YawPosition =     -105.14  },
            new WindirYawpos { WinDir =     5.5 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     5.4 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     5.3 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     5.2 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     5.1 , YawPosition =     -109.37  },
            new WindirYawpos { WinDir =     5   , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     4.9 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     4.8 , YawPosition =     -104.91  },
            new WindirYawpos { WinDir =     4.7 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     4.6 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     4.5 , YawPosition =     -109.37  },
            new WindirYawpos { WinDir =     4.4 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     4.3 , YawPosition =     -104.69  },
            new WindirYawpos { WinDir =     4.2 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     4.1 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     4   , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     3.9 , YawPosition =     -109.37  },
            new WindirYawpos { WinDir =     3.8 , YawPosition =     -104.5   },
            new WindirYawpos { WinDir =     3.7 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     3.6 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     3.5 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     3.4 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     3.3 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     3.2 , YawPosition =     -104.39  },
            new WindirYawpos { WinDir =     3.1 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     3   , YawPosition =     -109.37  },
            new WindirYawpos { WinDir =     2.9 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     2.8 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     2.7 , YawPosition =     -109.37  },
            new WindirYawpos { WinDir =     2.6 , YawPosition =     -109.37  },
            new WindirYawpos { WinDir =     2.5 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     2.4 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     2.3 , YawPosition =     -109.37  },
            new WindirYawpos { WinDir =     2.2 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     2.1 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     2   , YawPosition =     -109.37  },
            new WindirYawpos { WinDir =     1.9 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     1.8 , YawPosition =     -109.37  },
            new WindirYawpos { WinDir =     1.7 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     1.6 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     1.5 , YawPosition =     -109.37  },
            new WindirYawpos { WinDir =     1.4 , YawPosition =     -109.37  },
            new WindirYawpos { WinDir =     1.3 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     1.2 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     1.1 , YawPosition =     -109.37  },
            new WindirYawpos { WinDir =     1   , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     0.9 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     0.8 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     0.7 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     0.6 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     0.5 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     0.4 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     0.3 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     0.2 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     0.1 , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     0   , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -0.1    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -0.2    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -0.3    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -0.4    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -0.5    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -0.6    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -0.7    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -0.8    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -0.9    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -1  , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -1.1    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -1.2    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -1.3    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -1.4    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -1.5    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -1.6    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -1.7    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -1.8    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -1.9    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -2  , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -2.1    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -2.2    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -2.3    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -2.4    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -2.5    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -2.6    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -2.7    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -2.8    , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -2.9    , YawPosition =     -110.92  },
            new WindirYawpos { WinDir =     -3  , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -3.1    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -3.2    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -3.3    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -3.4    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -3.5    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -3.6    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -3.7    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -3.8    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -3.9    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -4  , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -4.1    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -4.2    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -4.3    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -4.4    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -4.5    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -4.6    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -4.7    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -4.8    , YawPosition =     -115.49  },
            new WindirYawpos { WinDir =     -4.9    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -5  , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -5.1    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -5.2    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -5.3    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -5.4    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -5.5    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -5.6    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -5.7    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -5.8    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -5.9    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -6  , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -6.1    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -6.2    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -6.3    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -6.4    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -6.5    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -6.6    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -6.7    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -6.8    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -6.9    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -7  , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -7.1    , YawPosition =     -110.92  },
            new WindirYawpos { WinDir =     -7.2    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -7.3    , YawPosition =     -110.92  },
            new WindirYawpos { WinDir =     -7.4    , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -7.5    , YawPosition =     -104.96  },
            new WindirYawpos { WinDir =     -7.6    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -7.7    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -7.8    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -7.9    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -8  , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -8.1    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -8.2    , YawPosition =     -110.92  },
            new WindirYawpos { WinDir =     -8.3    , YawPosition =     -104.96  },
            new WindirYawpos { WinDir =     -8.400001   , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -8.5    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -8.6    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -8.7    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -8.8    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -8.900001   , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -9  , YawPosition =     -107.11  },
            new WindirYawpos { WinDir =     -9.1    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -9.2    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -9.3    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -9.400001   , YawPosition =     -110.92  },
            new WindirYawpos { WinDir =     -9.5    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -9.6    , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -9.7    , YawPosition =     -104.96  },
            new WindirYawpos { WinDir =     -9.8    , YawPosition =     -109.75  },
            new WindirYawpos { WinDir =     -9.900001   , YawPosition =     -104.41  },
            new WindirYawpos { WinDir =     -10 , YawPosition =     -112.04  },
            new WindirYawpos { WinDir =     -10.1   , YawPosition =     -104.96  },
            new WindirYawpos { WinDir =     -10.2   , YawPosition =     -110.92  },
            new WindirYawpos { WinDir =     -10.3   , YawPosition =     -104.96  },
            new WindirYawpos { WinDir =     -10.4   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -10.5   , YawPosition =     -109.3   },
            new WindirYawpos { WinDir =     -10.6   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -10.7   , YawPosition =     -104.96  },
            new WindirYawpos { WinDir =     -10.8   , YawPosition =     -108.44  },
            new WindirYawpos { WinDir =     -10.9   , YawPosition =     -105.45  },
            new WindirYawpos { WinDir =     -11 , YawPosition =     -114.23  },
            new WindirYawpos { WinDir =     -11.1   , YawPosition =     -104.95  },
            new WindirYawpos { WinDir =     -11.2   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -11.3   , YawPosition =     -115.82  },
            new WindirYawpos { WinDir =     -11.4   , YawPosition =     -112.93  },
            new WindirYawpos { WinDir =     -11.5   , YawPosition =     -104.96  },
            new WindirYawpos { WinDir =     -11.6   , YawPosition =     -104.96  },
            new WindirYawpos { WinDir =     -11.7   , YawPosition =     -112.93  },
            new WindirYawpos { WinDir =     -11.8   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -11.9   , YawPosition =     -108.92  },
            new WindirYawpos { WinDir =     -12 , YawPosition =     -110.92  },
            new WindirYawpos { WinDir =     -12.1   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -12.2   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -12.3   , YawPosition =     -104.96  },
            new WindirYawpos { WinDir =     -12.4   , YawPosition =     -109.1   },
            new WindirYawpos { WinDir =     -12.5   , YawPosition =     -113.96  },
            new WindirYawpos { WinDir =     -12.6   , YawPosition =     -104.96  },
            new WindirYawpos { WinDir =     -12.7   , YawPosition =     -110.92  },
            new WindirYawpos { WinDir =     -12.8   , YawPosition =     -113.27  },
            new WindirYawpos { WinDir =     -12.9   , YawPosition =     -105.45  },
            new WindirYawpos { WinDir =     -13 , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -13.1   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -13.2   , YawPosition =     -104.96  },
            new WindirYawpos { WinDir =     -13.3   , YawPosition =     -108.35  },
            new WindirYawpos { WinDir =     -13.4   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -13.5   , YawPosition =     -110.93  },
            new WindirYawpos { WinDir =     -13.6   , YawPosition =     -113.74  },
            new WindirYawpos { WinDir =     -13.7   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -13.8   , YawPosition =     -104.96  },
            new WindirYawpos { WinDir =     -13.9   , YawPosition =     -104.96  },
            new WindirYawpos { WinDir =     -14 , YawPosition =     -107.55  },
            new WindirYawpos { WinDir =     -14.1   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -14.2   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -14.3   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -14.4   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -14.5   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -14.6   , YawPosition =     -104.96  },
            new WindirYawpos { WinDir =     -14.7   , YawPosition =     -110.92  },
            new WindirYawpos { WinDir =     -14.8   , YawPosition =     -104.96  },
            new WindirYawpos { WinDir =     -14.9   , YawPosition =     -104.96  },
            new WindirYawpos { WinDir =     -15 , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -15.1   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -15.2   , YawPosition =     -104.96  },
            new WindirYawpos { WinDir =     -15.3   , YawPosition =     -104.96  },
            new WindirYawpos { WinDir =     -15.4   , YawPosition =     -110.92  },
            new WindirYawpos { WinDir =     -15.5   , YawPosition =     -104.96  },
            new WindirYawpos { WinDir =     -15.6   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -15.7   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -15.8   , YawPosition =     -105.45  },
            new WindirYawpos { WinDir =     -15.9   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -16 , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -16.1   , YawPosition =     -105.46  },
            new WindirYawpos { WinDir =     -16.2   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -16.3   , YawPosition =     -110.99  },
            new WindirYawpos { WinDir =     -16.4   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -16.5   , YawPosition =     -105.53  },
            new WindirYawpos { WinDir =     -16.6   , YawPosition =     -112.69  },
            new WindirYawpos { WinDir =     -16.7   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -16.8   , YawPosition =     -103.46  },
            new WindirYawpos { WinDir =     -16.9   , YawPosition =     -111.58  },
            new WindirYawpos { WinDir =     -17 , YawPosition =     -111.36  },
            new WindirYawpos { WinDir =     -17.1   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -17.2   , YawPosition =     -103.46  },
            new WindirYawpos { WinDir =     -17.3   , YawPosition =     -121.81  },
            new WindirYawpos { WinDir =     -17.4   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -17.5   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -17.6   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -17.7   , YawPosition =     -121.53  },
            new WindirYawpos { WinDir =     -17.8   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -17.9   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -18 , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -18.1   , YawPosition =     -111.93  },
            new WindirYawpos { WinDir =     -18.2   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -18.3   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -18.4   , YawPosition =     -125.72  },
            new WindirYawpos { WinDir =     -18.5   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -18.6   , YawPosition =     -113.13  },
            new WindirYawpos { WinDir =     -18.7   , YawPosition =     -124.81  },
            new WindirYawpos { WinDir =     -18.8   , YawPosition =     -103.46  },
            new WindirYawpos { WinDir =     -18.9   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -19 , YawPosition =     -103.46  },
            new WindirYawpos { WinDir =     -19.1   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -19.2   , YawPosition =     -121.96  },
            new WindirYawpos { WinDir =     -19.3   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -19.4   , YawPosition =     -124.62  },
            new WindirYawpos { WinDir =     -19.5   , YawPosition =     -103.46  },
            new WindirYawpos { WinDir =     -19.6   , YawPosition =     -125     },
            new WindirYawpos { WinDir =     -19.7   , YawPosition =     -103.46  },
            new WindirYawpos { WinDir =     -19.8   , YawPosition =     -124.6   },
            new WindirYawpos { WinDir =     -19.9   , YawPosition =     -103.46  },
            new WindirYawpos { WinDir =     -20 , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -20.1   , YawPosition =     -122.18  },
            new WindirYawpos { WinDir =     -20.2   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -20.3   , YawPosition =     -120.57  },
            new WindirYawpos { WinDir =     -20.4   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -20.5   , YawPosition =     -103.46  },
            new WindirYawpos { WinDir =     -20.6   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -20.7   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -20.8   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -20.9   , YawPosition =     -111.93  },
            new WindirYawpos { WinDir =     -21 , YawPosition =     -103.46  },
            new WindirYawpos { WinDir =     -21.1   , YawPosition =     -120.82  },
            new WindirYawpos { WinDir =     -21.2   , YawPosition =     -103.46  },
            new WindirYawpos { WinDir =     -21.3   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -21.4   , YawPosition =     -123.07  },
            new WindirYawpos { WinDir =     -21.5   , YawPosition =     -103.46  },
            new WindirYawpos { WinDir =     -21.6   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -21.7   , YawPosition =     -103.46  },
            new WindirYawpos { WinDir =     -21.8   , YawPosition =     -103.46  },
            new WindirYawpos { WinDir =     -21.9   , YawPosition =     -123.74  },
            new WindirYawpos { WinDir =     -22 , YawPosition =     -103.46  },
            new WindirYawpos { WinDir =     -22.1   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -22.2   , YawPosition =     -103.46  },
            new WindirYawpos { WinDir =     -22.3   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -22.4   , YawPosition =     -113.46  },
            new WindirYawpos { WinDir =     -22.5   , YawPosition =     -111.93  },
            new WindirYawpos { WinDir =     -22.6   , YawPosition =     -124.1   },
            new WindirYawpos { WinDir =     -22.7   , YawPosition =     -103.46  },
            new WindirYawpos { WinDir =     -22.8   , YawPosition =     -103.46  },
            new WindirYawpos { WinDir =     -22.9   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -23 , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -23.1   , YawPosition =     -111.93  },
            new WindirYawpos { WinDir =     -23.2   , YawPosition =     -103.46  },
            new WindirYawpos { WinDir =     -23.3   , YawPosition =     -113.24  },
            new WindirYawpos { WinDir =     -23.4   , YawPosition =     -103.46  },
            new WindirYawpos { WinDir =     -23.5   , YawPosition =     -103.46  },
            new WindirYawpos { WinDir =     -23.6   , YawPosition =     -103.46  },
            new WindirYawpos { WinDir =     -23.7   , YawPosition =     -111.93  },
            new WindirYawpos { WinDir =     -23.8   , YawPosition =     -111.93  },
            new WindirYawpos { WinDir =     -23.9   , YawPosition =     -103.46  },
            new WindirYawpos { WinDir =     -24 , YawPosition =     -103.46  },
            new WindirYawpos { WinDir =     -24.1   , YawPosition =     -103.46  },
            new WindirYawpos { WinDir =     -24.2   , YawPosition =     -103.46  },
            new WindirYawpos { WinDir =     -24.3   , YawPosition =     -111.93  },
            new WindirYawpos { WinDir =     -24.4   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -24.5   , YawPosition =     -122.56  },
            new WindirYawpos { WinDir =     -24.6   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -24.7   , YawPosition =     -122.79  },
            new WindirYawpos { WinDir =     -24.8   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -24.9   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -25 , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -25.1   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -25.2   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -25.3   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -25.4   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -25.5   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -25.6   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -25.7   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -25.8   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -25.9   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -26 , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -26.1   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -26.2   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -26.3   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -26.4   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -26.5   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -26.6   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -26.7   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -26.8   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -26.9   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -27 , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -27.1   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -27.2   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -27.3   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -27.4   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -27.5   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -27.6   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -27.7   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -27.8   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -27.9   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -28 , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -28.1   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -28.2   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -28.3   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -28.4   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -28.5   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -28.6   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -28.7   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -28.8   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -28.9   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -29 , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -29.1   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -29.2   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -29.3   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -29.4   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -29.5   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -29.6   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -29.7   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -29.8   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -29.9   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -30 , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -30.1   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -30.2   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -30.3   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -30.4   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -30.5   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -30.6   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -30.7   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -30.8   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -30.9   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -31 , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -31.1   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -31.2   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -31.3   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -31.4   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -31.5   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -31.6   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -31.7   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -31.8   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -31.9   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -32 , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -32.1   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -32.2   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -32.3   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -32.4   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -32.5   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -32.6   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -32.7   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -32.8   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -32.9   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -33 , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -33.1   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -33.2   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -33.3   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -33.4   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -33.5   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -33.6   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -33.7   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -33.8   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -33.9   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -34 , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -34.1   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -34.2   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -34.3   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -34.4   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -34.5   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -34.6   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -34.7   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -34.8   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -35 , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -35.1   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -35.2   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -35.3   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -35.4   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -35.5   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -35.6   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -35.7   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -35.8   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -35.9   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -36 , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -36.1   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -36.2   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -36.3   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -36.4   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -36.5   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -36.6   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -36.7   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -36.8   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -36.9   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -37 , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -37.1   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -37.2   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -37.3   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -37.4   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -37.5   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -37.6   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -37.7   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -37.8   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -37.9   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -38 , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -38.1   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -38.2   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -38.3   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -38.4   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -38.5   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -38.6   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -38.7   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -38.8   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -38.9   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -39 , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -39.1   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -39.2   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -39.3   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -39.4   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -39.5   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -39.6   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -39.7   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -39.8   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -39.9   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -40 , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -40.1   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -40.2   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -40.3   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -40.4   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -40.5   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -40.6   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -40.7   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -40.8   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -40.9   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -41 , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -41.1   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -41.2   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -41.3   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -41.4   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -41.5   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -41.6   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -41.7   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -41.8   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -41.9   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -42 , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -42.1   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -42.2   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -42.3   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -42.4   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -42.5   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -42.6   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -42.7   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -42.8   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -42.9   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -43 , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -43.1   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -43.2   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -43.3   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -43.4   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -43.5   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -43.7   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -43.8   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -43.9   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -44 , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -44.2   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -44.4   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -44.5   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -44.6   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -44.7   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -44.8   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -44.9   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -45 , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -45.1   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -45.2   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -45.3   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -45.4   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -45.5   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -45.6   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -45.7   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -45.8   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -45.9   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -46 , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -46.1   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -46.2   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -46.3   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -46.5   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -46.6   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -46.7   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -46.9   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -47 , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -47.1   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -47.2   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -47.3   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -47.4   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -47.5   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -47.6   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -47.7   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -47.8   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -47.9   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -48 , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -48.2   , YawPosition =     -159.96  },
            new WindirYawpos { WinDir =     -48.3   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -48.8   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -49.3   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -49.7   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -50 , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -50.5   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -50.7   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -51.2   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -51.3   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -51.9   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -52 , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -52.4   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -52.6   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -52.7   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -53 , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -53.1   , YawPosition =     -133.87  },
            new WindirYawpos { WinDir =     -53.2   , YawPosition =     -133.87  }
        };
    }
}
